---

- name: "install python."
  become: true
  apt:
    name: ["python3"]
    state: latest
    update_cache: yes

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

# - name: "upgrade packages"
#   become: yes
#   apt:
#     upgrade: yes

- name: "install nodejs"
  become: yes
  apt:
    name: "nodejs"
    state: present
    update_cache: yes

- name: "install npm"
  become: yes
  apt:
    name: "npm"
    state: present
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    